production:
  adapter: PostgreSQL
  <% client = Aws::SSM::Client.new(region: 'eu-west-2') %>
  username: <%= client.get_parameter({ name: "/db/production/alpha-blog/user", with_decryption: false })[0][:value] %>
  password: <%= client.get_parameter({ name: "/db/production/alpha-blog/password", with_decryption: true })[0][:value] %>
  database: <%= client.get_parameter({ name: "/db/production/alpha-blog/dbname", with_decryption: false })[0][:value] %>
  port: <%= client.get_parameter({ name: "/db/production/alpha-blog/port", with_decryption: false })[0][:value] %>
  url: postgresql://<%= client.get_parameter({ name: "/db/production/alpha-blog/host", with_decryption: false })[0][:value] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000